# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/Users/j48s677/Desktop/vivado_stuff/SEM/SEM/sem_0_ex/imports/sem_0_sem_example.xdc

# IP: ip/sem_0/sem_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sem_0 || ORIG_REF_NAME==sem_0} -quiet] -quiet

# TCL: c:/Users/j48s677/Desktop/vivado_stuff/SEM/SEM/sem_0_ex/imports/makedata.tcl
