# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/j48s677/Desktop/vivado_stuff/SEM/SEM/SEM_test/SEM_test.srcs/sources_1/ip/sem_0/sem_0.xci
# IP: The module: 'sem_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/j48s677/Desktop/vivado_stuff/SEM/SEM/SEM_test/SEM_test.gen/sources_1/ip/sem_0/synth/sem_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sem_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/j48s677/Desktop/vivado_stuff/SEM/SEM/SEM_test/SEM_test.srcs/sources_1/ip/sem_0/sem_0.xci
# IP: The module: 'sem_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/j48s677/Desktop/vivado_stuff/SEM/SEM/SEM_test/SEM_test.gen/sources_1/ip/sem_0/synth/sem_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sem_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
